### ISSUE TITLE
Is Pulumi package required?

### ISSUE THREAD

**Issue by taylorhlabs** [leerob/nextjs-gcp-storage#1]
Hey @leerob - thanks for putting together this example. This is not really an issue but I didn't know where else to put it. **I have a couple questions about how Pulumi is used in your example. Essentially, what does Pulumi do that the GCP package doesn't and why use Pulumi in a GCP project?**

After following your steps for Option 2 (Create bucket), I have your example working in my lab and uploading files to my GCP bucket. If my app just uploads all my files to a single bucket (meaning I don't need my app to be able to create buckets), do I need to include Pulumi in my project?  It looks like you have an example for creating a new bucket in the index.js file Otherwise, it seems that your code for uploading files does not require the Pulumi packages. Is this an accurate conclusion on my part?

From a setup perspective, it looks like you use Pulumi to create the bucket initially but if I already have a GCP bucket or create one using another process, I don't need Pulumi. Is this also an accurate conclusion?

Thanks again for the awesome example!

**Comment by leerob** [comment]
No, Pulumi isn't required. It just simplifies [Infrastructure as Code](https://www.hashicorp.com/resources/what-is-infrastructure-as-code).

**Comment by taylorhlabs** [comment]
Great, thanks for clarifying.
